import Product, { ProductDocument } from '../models/Product';
import { PaginatedResult } from '../types';
import { ProductFilters, CreateProductDTO, UpdateProductDTO } from '../types/dto';

/**
 * Build a MongoDB query object from product filters.
 * Always includes { isActive: true } to exclude soft-deleted products.
 */
export function buildProductQuery(filters: ProductFilters): Record<string, any> {
  const query: Record<string, any> = { isActive: true };

  if (filters.team) {
    query.team = { $regex: filters.team, $options: 'i' };
  }

  if (filters.category) {
    query.category = filters.category;
  }

  if (filters.size) {
    query.sizes = {
      $elemMatch: { size: filters.size, stock: { $gt: 0 } },
    };
  }

  if (filters.priceMin || filters.priceMax) {
    query.price = {};
    if (filters.priceMin) query.price.$gte = filters.priceMin;
    if (filters.priceMax) query.price.$lte = filters.priceMax;
  }

  if (filters.jerseyType) {
    query.jerseyType = filters.jerseyType;
  }

  return query;
}

/**
 * Get MongoDB sort option from sortBy parameter.
 */
export function getSortOption(sortBy?: string): Record<string, 1 | -1> {
  switch (sortBy) {
    case 'price':
      return { price: 1 };
    case 'newest':
      return { createdAt: -1 };
    case 'popular':
      return { reviewCount: -1, rating: -1 };
    default:
      return { createdAt: -1 };
  }
}

/**
 * Get paginated products with filters and sorting.
 */
export async function getProducts(
  filters: ProductFilters
): Promise<PaginatedResult<ProductDocument>> {
  const page = filters.page || 1;
  const limit = filters.limit || 12;
  const skip = (page - 1) * limit;

  const query = buildProductQuery(filters);
  const sort = getSortOption(filters.sortBy);

  const [data, total] = await Promise.all([
    Product.find(query).sort(sort).skip(skip).limit(limit),
    Product.countDocuments(query),
  ]);

  const totalPages = Math.ceil(total / limit);

  return {
    data,
    total,
    page,
    totalPages,
    hasNext: page < totalPages,
  };
}

/**
 * Get a single product by ID.
 */
export async function getProductById(id: string): Promise<ProductDocument | null> {
  return Product.findOne({ _id: id, isActive: true });
}

/**
 * Get a single product by ID or slug.
 * Tries to find by MongoDB ObjectId first, then falls back to slug lookup.
 */
export async function getProductByIdOrSlug(idOrSlug: string): Promise<ProductDocument | null> {
  // Check if the parameter looks like a MongoDB ObjectId (24 hex chars)
  const isObjectId = /^[0-9a-fA-F]{24}$/.test(idOrSlug);

  if (isObjectId) {
    return Product.findOne({ _id: idOrSlug, isActive: true });
  }

  // Otherwise treat as slug
  return Product.findOne({ slug: idOrSlug, isActive: true });
}

/**
 * Create a new product.
 */
export async function createProduct(data: CreateProductDTO): Promise<ProductDocument> {
  const product = new Product({
    name: data.name,
    description: data.description,
    price: data.price,
    compareAtPrice: data.compareAtPrice,
    images: data.images,
    category: data.category,
    team: data.team,
    player: data.player,
    jerseyType: data.jerseyType,
    sizes: data.sizes,
    tags: data.tags,
    isFeatured: data.isFeatured ?? false,
    isLimitedDrop: data.isLimitedDrop ?? false,
    allowCustomization: data.allowCustomization ?? false,
  });

  return product.save();
}

/**
 * Update an existing product by ID.
 */
export async function updateProduct(
  id: string,
  data: UpdateProductDTO
): Promise<ProductDocument | null> {
  const product = await Product.findById(id);
  if (!product) return null;

  // Apply updates
  Object.assign(product, data);

  // If name changed, slug will be regenerated by pre-save hook
  return product.save();
}

/**
 * Soft delete a product by setting isActive to false.
 */
export async function deleteProduct(id: string): Promise<ProductDocument | null> {
  return Product.findByIdAndUpdate(id, { isActive: false }, { new: true });
}

/**
 * Search products using MongoDB full-text search.
 */
export async function searchProducts(query: string): Promise<ProductDocument[]> {
  return Product.find({
    $text: { $search: query },
    isActive: true,
  }).sort({ score: { $meta: 'textScore' } });
}

/**
 * Get related products based on same team or category, excluding the current product.
 */
export async function getRelatedProducts(
  productId: string,
  limit: number = 4
): Promise<ProductDocument[]> {
  const product = await Product.findById(productId);
  if (!product) return [];

  return Product.find({
    _id: { $ne: productId },
    isActive: true,
    $or: [{ team: product.team }, { category: product.category }],
  }).limit(limit);
}
